#pragma once

#define VIAL_KEYBOARD_UID { 0x97, 0xD0, 0xA5, 0x97, 0x57, 0x48, 0xD0, 0x4F }
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define EE_HANDS

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define DYNAMIC_KEYMAP_MACRO_COUNT 32

#define UNICODE_SELECTED_MODES \
    UNICODE_MODE_LINUX,        \
    UNICODE_MODE_WINCOMPOSE,   \
    UNICODE_MODE_MACOS
